### ISSUE TITLE
Field with the name (v1+themes|post|inherited) already exists in this container

### ISSUE THREAD

**Issue by uBadRequest** [KissPeter/APIFuzzer#37]
What does this error mean?

```
[INFO    ][fuzz_request_sender.__init__] Logger initialized
Traceback (most recent call last):
  File "fuzzer.py", line 158, in <module>
    prog.run()
  File "fuzzer.py", line 54, in run
    model.connect(template.compile_template())
  File "/root/tools/APIFuzzer/apifuzzer/base_template.py", line 43, in compile_template
    template.append_fields([Container(name=name, fields=field)])
  File "/usr/local/lib/python3.8/dist-packages/kitty/model/low_level/container.py", line 65, in __init__
    self.replace_fields(fields)
  File "/usr/local/lib/python3.8/dist-packages/kitty/model/low_level/container.py", line 333, in replace_fields
    self.append_fields(new_fields)
  File "/usr/local/lib/python3.8/dist-packages/kitty/model/low_level/container.py", line 253, in append_fields
    self.push(field)
  File "/usr/local/lib/python3.8/dist-packages/kitty/model/low_level/container.py", line 320, in push
    raise KittyException('field with the name (%s) already exists in this container' % (name))
kitty.core.KittyException: field with the name (v1+themes|post|inherited) already exists in this container
```

**Comment by KissPeter** [comment]
Hi
It is a bug in my code.
Could you please provide the API definition?

**Comment by KissPeter** [comment]
Please try to reproduce the issue on the Dev branch.

**Comment by uBadRequest** [comment]
This happened during a pentest and I no longer have access to the instance that I had credentials for. I guess I could try it unauthenticated against another one instance I don't have credentials to.

**Comment by KissPeter** [comment]
For reproducting the issue you need the API definition only as the issue was in my code.

**Comment by KissPeter** [comment]
closing due to inactivity, potential fix ready in dev branch

**Comment by ibessolitsyn** [comment]
@KissPeter how to make dev branch work since I got the same error?
