### ISSUE TITLE
Path items with no variables prevent the fuzzer from running

### ISSUE THREAD

**Issue by mbeckerle-xqueue** [KissPeter/APIFuzzer#48]
**Describe the bug**

I have a set of generated YAML and some contain a single path item with a single operation and instead of accepting it, the fuzzer gives an assertion error and stops processing. If I add another node, i.e. a second operation or even a nonsense parameter,the parser accepts the yaml and the fuzzing starts. I understand that this happens as the fuzzer sees "nothing to do" for this path item and defines this as "invalid", even if the OpenAPI YAML is valid according to the definition.

I would expect the parser to ignore this path item and just shut down instead of throwing an assertion error.

**APIFuzzer debug log**

```
3506003 [   INFO] APIFuzzer.OpenAPITemplateGenerator [openapi_template_generator.py:108 - process_api_resources ]: Start preparation
3506003 [   INFO] APIFuzzer.OpenAPITemplateGenerator [openapi_template_generator.py:152 - _process_api_resources ]: Resource: /blacklists Method: get
3506003 [  DEBUG] APIFuzzer.OpenAPITemplateGenerator [openapi_template_generator.py:78 -        _get_template ]: Open new Fuzz template for blacklists|get
3506003 [   INFO] APIFuzzer.BaseTemplate [base_template.py:51 -             get_stat ]: Template size: 0, content: {'params': set(), 'headers': set(), 'data': set(), 'path_variables': set(), 'cookies': set(), 'query': set(), 'content_type': ''}
3506003 [  DEBUG] APIFuzzer.OpenAPITemplateGenerator [openapi_template_generator.py:328 -     compile_base_url ]: Using openapi style url: http://localhost:8080/api
3506003 [   INFO] APIFuzzer.FuzzerTarget [fuzz_request_sender.py:36 -             __init__ ]: Logger initialized
3506003 [   INFO] APIFuzzer.OpenApiServerFuzzer [server_fuzzer.py:38 -             __init__ ]: Logger initialized
Traceback (most recent call last):
  File "./APIFuzzer", line 101, in <module>
    prog.run()
  File "/home/secretuser/APIFuzzer/APIFuzzer/apifuzzer/fuzzer.py", line 66, in run
    fuzzer.set_model(model)
  File "/home/secretuser/.local/lib/python3.8/site-packages/kitty/fuzzers/base.py", line 256, in set_model
    self.handle_stage_changed(model)
  File "/home/secretuser/.local/lib/python3.8/site-packages/kitty/fuzzers/base.py", line 404, in handle_stage_changed
    stages = model.get_stages()
  File "/home/secretuser/.local/lib/python3.8/site-packages/kitty/model/high_level/graph.py", line 223, in get_stages
    sequence = self.get_sequence()
  File "/home/secretuser/.local/lib/python3.8/site-packages/kitty/model/high_level/base.py", line 154, in get_sequence
    self._get_ready()
  File "/home/secretuser/.local/lib/python3.8/site-packages/kitty/model/high_level/graph.py", line 101, in _get_ready
    assert len(self._sequences)
AssertionError

```

**Related API definition**

My failing definition looks like this:
```
---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
servers:
  - url: http://localhost:8080/api
paths:
  /blacklists:
    get:
      responses:
        "200":
          description: OK
          content:
            application/vnd.maileon.api+xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blacklist'
components:
  schemas:
    Blacklist:
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        entries:
          type: array
          items:
            type: string
```

**Software environment (please complete the following information):**

- OS: Ubuntu 20.04.3 LTS
- Python version: Python 3.8.10
- APIFuzzer Version: 0.9.12

**Comment by mbeckerle-xqueue** [comment]
After thinking about the usecase it is probably more a feature request than a bug, so I will close this.
